# Code Quality Check file for mvn applicaion
name: Code Quality check

on:
    workflow_call:


jobs:
    validate:
        runs-on: ubuntu-latest
        services:
            mysql:
              image: mysql:8.0
              env:
                MYSQL_ROOT_PASSWORD: root
                MYSQL_DATABASE: bankappdb
              ports:
                - 3306:3306
              options: |
                --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
                --health-interval=10s
                --health-timeout=5s
                --health-retries=5


        steps:
            - name: checkout code
              uses: actions/checkout@v4
            
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '21'
    

            - name: Set up Maven
              uses: stCarolas/setup-maven@v5
              with:
                maven-version: 3.9.16 #3.8.2
            
            - name: Maven Enforce
              run: mvn -B validate
            
            #- name: Build with Maven
            #  run: mvn -B verify spotbugs:spotbugs
            
            - name: Build + SpotBugs + Tests
              run:  mvn -B clean verify # mvn -B clean verify spotbugs:spotbugs spotbugs:check

            - name: SonarQube Scan
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: |
                mvn -B sonar:sonar \
                    -Dsonar.projectKey=my-java-app \
                    -Dsonar.host.url=https://sonar.mycompany.com \
                    -Dsonar.login=${SONAR_TOKEN}

            - name: SonarQube Quality Gate Check
              run: mvn -B sonar-quality-gate:check
              timeout-minutes: 5
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            # Triggering SonarQube analysis as results of it are required by Quality Gate check.
            - name: SonarQube Scan
              uses: sonarsource/sonarqube-scan-action@master
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

            # Check the Quality Gate status.
            - name: SonarQube Quality Gate check
              id: sonarqube-quality-gate-check
              uses: sonarsource/sonarqube-quality-gate-action@master
              with:
                pollingTimeoutSec: 600
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


