name: DevSecOps pipline

on:
    push:
        branches:
            [main] 
    #workflow_dispatch:

jobs:
    # CI
    code_quality:
        uses: ./.github/workflows/code_quality.yml
    secret-scan:
        uses: ./.github/workflows/secrete_scan.yml
        secrets: inherit
        permissions:
            contents: read
            security-events: write 

    #dependency-scan:
    #    uses: ./.github/workflows/dependency_check.yml

    #dockerfile-scan:
    #    uses: ./.github/workflows/docker_scan.yml
    #    secrets: inherit