name: DevSecOps pipline

on:
    push:
        branches:
            [main] 
    #workflow_dispatch:

jobs:
    # CI
    #code_quality:
    #    uses: ./.github/workflows/code_quality.yml
    #    secrets: inherit
    secret-scan:
        uses: ./.github/workflows/secrete_scan.yml
        secrets: inherit
        permissions:
            contents: read
            security-events: write 

    #dependency-scan:
    #    uses: ./.github/workflows/dependency_check.yml
    #    secrets: inherit

    dockerfile-scan:
        needs: [secret-scan ] #[code_quality, dependency-scan, secret-scan] 
        uses: ./.github/workflows/docker_scan.yml
        secrets: inherit
    
    build-and-push:
        needs: [dockerfile-scan]
        uses: ./.github/workflows/build_and_push.yml
        secrets: inherit

    image-scan:
        needs: [ build-and-push]
        uses: ./.github/workflows/image_scan.yml
        secrets: inherit

    #deploy: 
    #    needs: [image-scan]
    #    uses: ./.github/workflows/deploy_to_server.yml
    #    secrets: inherit
