name: Secrete Scan

on:
    workflow_call:

jobs:
    secrete-scan:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write   # needed if you want SARIF uploaded to Code Scanning
        steps:
            - name: checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
              
            - name: Run Gitleaks Scanner
              uses: gitleaks/gitleaks-action@v3
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # github acitons manages it 
            
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                distribution: temurin
                java-version: 21
            
            - name: Build with Maven
              run: ./mvnw -B clean package -DskipTests
            
            - name: Run SpotBugs with FindSecBugs
              uses: advanced-security/spotbugs-findsecbugs-action@v1
              with:
                spotbugs_target: 'target'          # where Maven puts classes & jars
                spotbugs_filename_glob: '*.jar'    # scan the built JAR(s)
                upload_sarif: true                 # uploads results to GitHub Code Scanning
            