name: Secrete Scan

on:
    workflow_call:

jobs:
    secrete-scan:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write   # needed if you want SARIF uploaded to Code Scanning
        steps:
            - name: checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                        
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                distribution: temurin
                java-version: 21
              
            - name: Run Gitleaks Scanner
              uses: gitleaks/gitleaks-action@v3
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # github acitons manages it 

            

            